### ISSUE TITLE
Kayla Testing Work

### ISSUE THREAD

**Issue by stephpenn1** [ess-dive-community/essdive-soil-respiration#2]
Kayla, thanks again for looking at this reporting format. Here is what we'd like you do look at specifically.

### Main goal: Test out using real data
- [ ] find one of your rs datasets. we recommend you start with one that is relatively simple, but we'd like for it to be as realistic as possible to what you'd submit to a data repository for archival
- [ ] starting on the [main repository page](https://github.com/ess-dive-community/essdive-soil-respiration), follow the instructions for adopting the reporting format, **making note of anything that is difficult to navigate or confusing**

#### Things we'd like to know from this exercise:
- is the standard straightforward to use?
- do you think the required variables are sufficient?
- how was navigating from page to page?

_NOTE: feedback can be anything you find confusing, even if you figure things out eventually. we want to get a sense of the full user experience. be as nitpick-y as possible._

### Secondary goal: Test out contributions
- [ ] currently, we accept feedback and suggestions through Github issues. it would be great if you could organize some of your main feedback and add them as issues. see the ["How to contribute"](https://github.com/ess-dive-community/essdive-soil-respiration#how-to-contribute) section for further instructions

#### Things we'd like to know from this exercise:
- the contributions issues are separated into templates. how do you think these look? do they represent and/or satisfy the type of feedback you are looking to give?

**Comment by bpbond** [comment]
> it can be as complicated or simple as you'd like

Maybe "we recommend you start with one that's relatively simple"?

>be as nitpick-y as possible.

😆 👍
