### ISSUE TITLE
Test of Rs standards guidelines 

### ISSUE THREAD

**Issue by kaylamathes** [ess-dive-community/essdive-soil-respiration#3]
* Documentation reference (URL): https://github.com/ess-dive-community/essdive-soil-respiration
* Submitter: Kayla Mathes 
* Justification (why is this change necessary?): Cleaning up links, conflicting information and flow of instructions 

I suggest the following changes: 

Issues with instruction flow and links:
 
1. The front page could be slightly simplified. Some of the additional links are redundant with links already in the step-by-step guide and I think this could be slightly confusing. Consider either adding a "Quick Reference" heading if you want active users to be able to reference these links quickly, or just embed them all in the tutorial link. 
2. The "Data Template" link in the instructions does appear to have a way to download the template. Maybe it is my limited knowledge of Github, but it is not clear to me how to use this template. 
3. The "Data format Guide" link in the instruction page is actually the "meta data format guide" 
4. The Meta data template" link in the instruction page is not currently working

Issues/feedback with variables: 

1. The variable "Dry_CO2" is listed as optional in the "data format guide" link and required on the general instruction page. Also, I don't know if this is something you can fix, given the volume and variety of data people work with, but the LICOR-6400 I am working with labels this variable as "CO2s". Maybe include a couple different common variable titles on different machines to help users identify this variable? This could go for other important variables as well. 

2. Consider reordering variable list in the "data format guide" and the "meta data format guide" with required variables first, followed by optional ones. Right now, they are intermixed. 

3. Again, this may be in issue specific to the Licor-6400 and how I have it set up. But, using my data, for each given efflux run, the licor output provides only the end timestamp value. I could infer the beginning from the end of the previous measurement, how ever, it is not intuitive. Is there a specific reason why both timestamp values need to be included? Maybe an optional variable could be measurement length in seconds? 

4. Additional variables to consider including as either required or optional: 
       -"Run number" or an indicator of how many complete measurement cycles were collected at a given collar. 
        -Date of last precipitation in the meta-data variable list
         -Date of last instrument calibration. 

5. If you are going to separate the types of Issues/contributions, I would consider adding a "general" type to make it easier for people to list multiple types of feedback into one post.

**Comment by wavingtowaves** [comment]
I am looking forward to working on these changes @kaylamathes, but for now want to thank you for all the work you did to compile this list 👍🏻

**Comment by bpbond** [comment]
(Echoing Rob's comments above—thank you @kaylamathes !)

>Is there a specific reason why both timestamp values need to be included? Maybe an optional variable could be measurement length in seconds?

Good question. Yes, either one of those two options would in theory work; the crucial point is that we want to know the exact measurement period (start and stop). We ended up going with this solution for consistency with Ameriflux and FLUXNET.

**Comment by stephpenn1** [comment]
Thank you for the feedback! I have an upcoming deadline on another project so I will return to this at the end of April
